namespace Kindred.Rewards.Core.WebApi.Payloads;

public class ReportingApiModel
{
    public string Purpose { get; set; }
    public string SubPurpose { get; set; }
    public string Name { get; set; }
    public string Comments { get; set; }
    public string CustomerFacingName { get; set; }
    public string RewardRules { get; set; }
    public bool IsNameAutoGenerated { get; set; }
    public string CancellationReason { get; set; }
    public bool IsCancelled { get; set; }
    public string CreatedBy { get; set; }
    public DateTime CreatedOn { get; set; }
    public string UpdatedBy { get; set; }
    public DateTime UpdatedOn { get; set; }
    public IEnumerable<string> Tags { get; set; }
}
