using AutoMapper;

using Kindred.Rewards.Core.Enums;
using Kindred.Rewards.Core.Models;
using Kindred.Rewards.Core.Models.RewardConfiguration;
using Kindred.Rewards.Plugin.FreeBet.Models;

namespace Kindred.Rewards.Plugin.FreeBet.Mappings;

public class FreebetApiToDomainMapping : Profile
{
    public FreebetApiToDomainMapping()
    {
        CreateMap<FreeBetRewardRequest, RewardDomainModel>(MemberList.None)
            .ForMember(d => d.CustomerId, opt => opt.MapFrom(s => s.CustomerId))
            .ForMember(d => d.Name, opt => opt.MapFrom(s => s.Name))
            .ForMember(d => d.Comments, opt => opt.MapFrom(s => s.Comments))
            .ForMember(d => d.Category, opt => opt.MapFrom(_ => RewardCategory.RiskFree))
            .ForMember(d => d.Type, opt => opt.MapFrom(s => RewardType.Freebet))
            .ForMember(d => d.RewardId, opt => opt.MapFrom(s => Guid.NewGuid().ToString()))
            .ForMember(d => d.Tags, opt => opt.MapFrom(s => s.Tags))
            .ForMember(d => d.IsNameAutoGenerated, opt => opt.MapFrom(s => s.IsNameAutoGenerated))
            .ForMember(d => d.CountryCode, opt => opt.MapFrom(s => s.CountryCode))
            .ForMember(d => d.Jurisdiction, opt => opt.MapFrom(s => s.Jurisdiction))
            .ForMember(d => d.State, opt => opt.MapFrom(s => s.State))
            .ForMember(d => d.Brand, opt => opt.MapFrom(s => s.Brand))
            .ForMember(d => d.Purpose, opt => opt.MapFrom(s => s.Purpose))
            .ForMember(d => d.SubPurpose, opt => opt.MapFrom(s => s.SubPurpose))
            .ForMember(d => d.CustomerFacingName, opt => opt.MapFrom(s => s.CustomerFacingName))
            .ForMember(d => d.CurrencyCode, opt => opt.MapFrom(s => s.CurrencyCode))
            .ForMember(d => d.CreatedBy, opt => opt.MapFrom(s => s.CreatedBy))
            .ForMember(d => d.UpdatedBy, opt => opt.MapFrom(s => s.UpdatedBy))
            .ForPath(d => d.Terms.Restrictions, opt => opt.MapFrom(s => s.Restrictions))
            .AfterMap(
                (request, model) =>
                {
                    model.Terms.RewardParameters = Extensions.Extensions.MapFromRewardParametersToDictionary(request.RewardParameters, RewardType.Freebet.ToString());
                    model.Terms.Restrictions.Reload =
                        Extensions.Extensions.MapFromRewardParametersToRewardReload(request.RewardParameters, RewardType.Freebet.ToString());

                    model.Terms.Attributes = new Dictionary<string, string>();

                    if (request.DomainRestriction?.MultiConfig?.MinStages != null)
                    {
                        model.Terms.RewardParameters[RewardParameterKey.MinStages] = request.DomainRestriction?.MultiConfig?.MinStages?.ToString();
                    }

                    if (request.DomainRestriction?.MultiConfig?.MaxStages != null)
                    {
                        model.Terms.RewardParameters[RewardParameterKey.MaxStages] = request.DomainRestriction?.MultiConfig?.MaxStages?.ToString();
                    }

                    if (request.DomainRestriction?.MultiConfig?.MinCombinations != null)
                    {
                        model.Terms.RewardParameters[RewardParameterKey.MinCombinations] = request.DomainRestriction?.MultiConfig?.MinCombinations?.ToString();
                    }

                    if (request.DomainRestriction?.MultiConfig?.MaxCombinations != null)
                    {
                        model.Terms.RewardParameters[RewardParameterKey.MaxCombinations] = request.DomainRestriction?.MultiConfig?.MaxCombinations?.ToString();
                    }

                    if (request.DomainRestriction?.MultiConfig?.FilterFormulae != null)
                    {
                        model.Terms.RewardParameters[RewardParameterKey.AllowedFormulae] = string.Join(",", request.DomainRestriction.MultiConfig.FilterFormulae);
                    }

                    foreach (var attribute in request.Attributes)
                    {
                        model.Terms.Attributes.Add(attribute.Key, attribute.Value);
                    }

                    model.Terms.Restrictions.AllowedContestRefs = request.DomainRestriction?.FilterContestRefs;
                    model.Terms.Restrictions.AllowedContestTypes = request.DomainRestriction?.FilterContestTypes;
                    model.Terms.Restrictions.AllowedContestCategories = request.DomainRestriction?.FilterContestCategories;
                    model.Terms.Restrictions.AllowedOutcomes = request.DomainRestriction?.FilterOutcomes;

                    var contestStatus = request.DomainRestriction?.FilterContestStatuses?.ToString();
                    model.Terms.Restrictions.AllowedContestStatuses = string.IsNullOrWhiteSpace(contestStatus) ? null : Enum.Parse<ContestStatus>(contestStatus);

                    model.Terms.Restrictions.OddLimits = new() { MinimumStageOdds = request.DomainRestriction?.OddLimits?.MinimumStageOdds, MinimumCompoundOdds = request.DomainRestriction?.OddLimits?.MinimumCompoundOdds };

                });
    }
}
