namespace Kindred.Rewards.Core.Infrastructure.Data.DataModels;

public class Reward : BaseEditableDataModel<string>
{

    public string RewardType { get; set; } // eg FreeBet

    public string CustomerId { get; set; }

    public string Purpose { get; set; }

    public string SubPurpose { get; set; }

    public string Name { get; set; }

    public string CurrencyCode { get; set; }

    public string Comments { get; set; }

    public string RewardRules { get; set; }

    public bool IsNameAutoGenerated { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string ContestStatus { get; set; }

    private DateTime _expiryDateTime;

    private DateTime _startDateTime;

    public DateTime StartDateTime
    {
        get => _startDateTime;
        set => _startDateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    }

    public DateTime ExpiryDateTime
    {
        get => _expiryDateTime;
        set => _expiryDateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    }

    public string TermsJson { get; set; }


    public virtual ICollection<RewardTag> RewardTags { get; set; }

    public List<AuditReward> Audits { get; set; }

    public string CountryCode { get; set; }

    public string Jurisdiction { get; set; }
    public string State { get; set; }

    public string Brand { get; set; }

    public string CustomerFacingName { get; set; }

    public bool IsCancelled { get; set; }

    public string CancellationReason { get; set; }

    public string SourceInstanceId { get; set; }

    public List<RewardTemplateReward> RewardTemplateReward { get; set; }

    public bool IsSystemGenerated { get; set; }

    public bool IsLocked { get; set; }

    public virtual ICollection<CustomerReward> CustomerRewards { get; set; }
}
