using Microsoft.EntityFrameworkCore.Migrations;

namespace Kindred.Rewards.Rewards.Repositories.Migrations;

public partial class AddIsNameAutoGeneratedAndRemoveNamingConvention : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "NamingConvention",
            table: "Reward");

        migrationBuilder.RenameColumn(
            name: "NamingConvention",
            table: "RewardClaim",
            newName: "RewardName");

        migrationBuilder.AddColumn<bool>(
            name: "IsNameAutoGenerated",
            table: "Reward",
            type: "boolean",
            nullable: false,
            defaultValue: false);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "IsNameAutoGenerated",
            table: "Reward");

        migrationBuilder.RenameColumn(
            name: "RewardName",
            table: "RewardClaim",
            newName: "NamingConvention");

        migrationBuilder.AddColumn<string>(
            name: "NamingConvention",
            table: "Reward",
            type: "character varying(2000)",
            maxLength: 2000,
            nullable: false,
            defaultValue: "");
    }
}
