// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Kindred.Rewards.Rewards.FunctionalTests.Features.Profitboost.Variants
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ProfitboostWithMaxExtraWinningsConfigured")]
    [NUnit.Framework.IgnoreAttribute("Ignored feature")]
    [NUnit.Framework.CategoryAttribute("Acceptance")]
    [NUnit.Framework.CategoryAttribute("variants")]
    [NUnit.Framework.CategoryAttribute("maxExtraWinnings")]
    [NUnit.Framework.CategoryAttribute("profitboost")]
    public partial class ProfitboostWithMaxExtraWinningsConfiguredFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "Acceptance",
                "variants",
                "maxExtraWinnings",
                "profitboost",
                "ignore"};
        
#line 1 "ProfitboostWithMaxExtraWinningsConfigured.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Profitboost/Variants", "ProfitboostWithMaxExtraWinningsConfigured", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table129 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "rewardType",
                        "legTable",
                        "allowedFormulae",
                        "customer_id",
                        "minStages",
                        "maxStages",
                        "minCombinations",
                        "maxCombinations",
                        "maxExtraWinnings"});
            table129.AddRow(new string[] {
                        "profitboost_bonus",
                        "profitboost",
                        "{\"1\":\"10\",\"2\":\"10\",\"4\":\"0\"}",
                        "singles,doubles",
                        "918792",
                        "1",
                        "15",
                        "1",
                        "2",
                        "1"});
#line 5
    testRunner.Given("I have bonuses in the system", ((string)(null)), table129, "Given ");
#line hidden
#line 8
    testRunner.Then("the HttpStatusCode should be 201", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table130 = new TechTalk.SpecFlow.Table(new string[] {
                        "customer_id",
                        "template_keys"});
            table130.AddRow(new string[] {
                        "918792",
                        "profitboost_bonus_user"});
#line 9
    testRunner.When("I submit GetEntitlement request for following criteria:", ((string)(null)), table130, "When ");
#line hidden
#line 12
    testRunner.Then("the HttpStatusCode should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table131 = new TechTalk.SpecFlow.Table(new string[] {
                        "bonus_name",
                        "promotion_name"});
            table131.AddRow(new string[] {
                        "profitboost_bonus",
                        ""});
#line 13
    testRunner.And("GetEntitlement response should include following rewards:", ((string)(null)), table131, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Claim with 2 stages where the reward payment is above the configured max extra wi" +
            "nnings")]
        public void ClaimWith2StagesWhereTheRewardPaymentIsAboveTheConfiguredMaxExtraWinnings()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Claim with 2 stages where the reward payment is above the configured max extra wi" +
                    "nnings", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table132 = new TechTalk.SpecFlow.Table(new string[] {
                            "customer_id",
                            "name",
                            "number_of_claims",
                            "stagePriceData"});
                table132.AddRow(new string[] {
                            "918792",
                            "profitboost_bonus",
                            "1",
                            "1.5,25.69"});
#line 18
    testRunner.When("I submit ClaimEntitlement request for following criteria for Currency \'AUD\':", ((string)(null)), table132, "When ");
#line hidden
#line 21
    testRunner.Then("the HttpStatusCode should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table133 = new TechTalk.SpecFlow.Table(new string[] {
                            "name"});
                table133.AddRow(new string[] {
                            "profitboost_bonus"});
#line 22
    testRunner.And("I expect following in the ClaimedEntitlements for the customerID=\'918792\':", ((string)(null)), table133, "And ");
#line hidden
                TechTalk.SpecFlow.Table table134 = new TechTalk.SpecFlow.Table(new string[] {
                            "name",
                            "bet_outcome",
                            "stake_amount",
                            "return_as_freebet",
                            "customer_id"});
                table134.AddRow(new string[] {
                            "profitboost_bonus",
                            "Winning",
                            "3.00",
                            "false",
                            "918792"});
#line 25
    testRunner.When("I settle the bet for following claim", ((string)(null)), table134, "When ");
#line hidden
#line 28
    testRunner.Then("I expect to receive RewardClaimSettledEvent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 29
    testRunner.And("I expect the correct Payout with rewardPaymentAmount of 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Claim with 2 stages where the reward payment is below the configured max extra wi" +
            "nnings")]
        public void ClaimWith2StagesWhereTheRewardPaymentIsBelowTheConfiguredMaxExtraWinnings()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Claim with 2 stages where the reward payment is below the configured max extra wi" +
                    "nnings", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table135 = new TechTalk.SpecFlow.Table(new string[] {
                            "customer_id",
                            "name",
                            "number_of_claims",
                            "stagePriceData"});
                table135.AddRow(new string[] {
                            "918792",
                            "profitboost_bonus",
                            "1",
                            "1,3.1"});
#line 32
    testRunner.When("I submit ClaimEntitlement request for following criteria for Currency \'AUD\':", ((string)(null)), table135, "When ");
#line hidden
#line 35
    testRunner.Then("the HttpStatusCode should be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table136 = new TechTalk.SpecFlow.Table(new string[] {
                            "name"});
                table136.AddRow(new string[] {
                            "profitboost_bonus"});
#line 36
    testRunner.And("I expect following in the ClaimedEntitlements for the customerID=\'918792\':", ((string)(null)), table136, "And ");
#line hidden
                TechTalk.SpecFlow.Table table137 = new TechTalk.SpecFlow.Table(new string[] {
                            "name",
                            "bet_outcome",
                            "stake_amount",
                            "return_as_freebet",
                            "customer_id"});
                table137.AddRow(new string[] {
                            "profitboost_bonus",
                            "Winning",
                            "3.00",
                            "false",
                            "918792"});
#line 39
    testRunner.When("I settle the bet for following claim", ((string)(null)), table137, "When ");
#line hidden
#line 42
    testRunner.Then("I expect to receive RewardClaimSettledEvent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 43
    testRunner.And("I expect the correct Payout with rewardPaymentAmount of 0.63", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
