using System.ComponentModel.DataAnnotations;

using Kindred.Rewards.Core.WebApi.Payloads;

namespace Kindred.Rewards.Plugin.ProfitBoost.Models;
public class ProfitBoostRewardRequest
{
    public string? CustomerId { get; set; }
    public DomainRestrictionApiModel DomainRestriction { get; set; }
    public string Name { get; set; }
    public string? CurrencyCode { get; set; }
    public bool IsNameAutoGenerated { get; set; }
    [StringLength(300)]
    public string? Comments { get; set; }

    [StringLength(2000, ErrorMessage = "RewardRules can not have more than 2000 characters.")]
    public string? RewardRules { get; set; }

    public RewardRestrictionApiModel Restrictions { get; set; }

    public ProfitBoostParametersApiModel RewardParameters { get; set; }

    public Dictionary<string, string> Attributes { get; set; } = new();

    public IEnumerable<string> Tags { get; set; } = Enumerable.Empty<string>();

    [Required]
    [StringLength(3, ErrorMessage = "CountryCode can not have more than 3 characters.")]
    public string CountryCode { get; set; }

    public string? Jurisdiction { get; set; }
    public string? State { get; set; }

    public string? Brand { get; set; }

    public string Purpose { get; set; }

    public string SubPurpose { get; set; }

    [StringLength(200)]
    public string CustomerFacingName { get; set; }

    public string? CreatedBy { get; set; }

    public string? UpdatedBy { get; set; }
}
